name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - dev
          - int

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    concurrency:
      group: deploy-${{ inputs.environment }}
      queue: max

    steps:
      - run: './scripts/deploy.sh'
